##
##  Makefile -- Build procedure for sample php_void Apache module
##  Autogenerated via ``apxs -n php_void -g''.
##

builddir=.
top_srcdir=/path/to/httpd
top_builddir=/path/to/httpd
include /path/to/httpd/build/special.mk

#   the used tools
APXS=apxs
APACHECTL=apachectl

#   additional defines, includes and libraries
#DEFS=-Dmy_define=my_value
#INCLUDES=-Imy/include/dir
#LIBS=-Lmy/lib/dir -lmylib

#   the default target
all: local-shared-build

#   install the shared object file into Apache 
install: install-modules

#   cleanup
clean:
	-rm -f mod_php_void.o mod_php_void.lo mod_php_void.slo mod_php_void.la 

#   simple test
test: reload
	lynx -mime_header http://localhost/php_void

#   install and activate shared object by reloading Apache to
#   force a reload of the shared object file
reload: install restart

#   the general Apache start/restart/stop
#   procedures
start:
	$(APACHECTL) start
restart:
	$(APACHECTL) restart
stop:
	$(APACHECTL) stop

